# -*- coding: utf-8 -*-



from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_monitorwindows(object):
    def setupUi(self, monitorwindows):
        monitorwindows.setObjectName("monitorwindows")
        monitorwindows.resize(380, 721)
        self.centralwidget = QtWidgets.QWidget(monitorwindows)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 80, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 80, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 440, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 280, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 520, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.laser_on_radiobtn = QtWidgets.QRadioButton(self.centralwidget)
        self.laser_on_radiobtn.setGeometry(QtCore.QRect(240, 470, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.laser_on_radiobtn.setFont(font)
        self.laser_on_radiobtn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.laser_on_radiobtn.setCheckable(True)
        self.laser_on_radiobtn.setAutoExclusive(False)
        self.laser_on_radiobtn.setObjectName("laser_on_radiobtn")
        self.apd_on_radiobtn = QtWidgets.QRadioButton(self.centralwidget)
        self.apd_on_radiobtn.setGeometry(QtCore.QRect(240, 550, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.apd_on_radiobtn.setFont(font)
        self.apd_on_radiobtn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.apd_on_radiobtn.setCheckable(True)
        self.apd_on_radiobtn.setAutoExclusive(False)
        self.apd_on_radiobtn.setObjectName("apd_on_radiobtn")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(240, 30, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setAutoExclusive(False)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(240, 310, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(70, 390, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(180, 390, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 130, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(40, 180, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(90, 130, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(250, 130, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 180, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 180, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 620, 93, 71))
        self.pushButton.setObjectName("pushButton")
        monitorwindows.setCentralWidget(self.centralwidget)

        self.retranslateUi(monitorwindows)
        QtCore.QMetaObject.connectSlotsByName(monitorwindows)

    def retranslateUi(self, monitorwindows):
        _translate = QtCore.QCoreApplication.translate
        monitorwindows.setWindowTitle(_translate("monitorwindows", "Monitor"))
        self.label.setText(_translate("monitorwindows", "Trap"))
        self.label_2.setText(_translate("monitorwindows", "Voltage"))
        self.label_3.setText(_translate("monitorwindows", "Frequency"))
        self.label_4.setText(_translate("monitorwindows", "Laser"))
        self.label_5.setText(_translate("monitorwindows", "Pressure"))
        self.label_6.setText(_translate("monitorwindows", "APD"))
        self.laser_on_radiobtn.setText(_translate("monitorwindows", "ON/OFF"))
        self.apd_on_radiobtn.setText(_translate("monitorwindows", "ON/OFF"))
        self.radioButton.setText(_translate("monitorwindows", "ON/OFF"))
        self.radioButton_2.setText(_translate("monitorwindows", "ON/OFF"))
        self.label_7.setText(_translate("monitorwindows", "TextLabel"))
        self.label_8.setText(_translate("monitorwindows", "[kPa]"))
        self.label_9.setText(_translate("monitorwindows", "Monitor"))
        self.label_10.setText(_translate("monitorwindows", "Set"))
        self.label_11.setText(_translate("monitorwindows", "TextLabel"))
        self.label_12.setText(_translate("monitorwindows", "TextLabel"))
        self.pushButton.setText(_translate("monitorwindows", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    monitorwindows = QtWidgets.QMainWindow()
    ui = Ui_monitorwindows()
    ui.setupUi(monitorwindows)
    monitorwindows.show()
    sys.exit(app.exec_())
