# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg
from pyqtgraph import PlotWidget
from PyQt5.QtWidgets import QDialog, QApplication, QFileDialog
import threading
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        pg.setConfigOption('background', 'w')
        pg.setConfigOption('foreground', 'k')


        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 721)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 811, 721))
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")

        """TAB APD"""

        self.tab_APD = QtWidgets.QWidget()
        self.tab_APD.setObjectName("tab_APD")
        self.graph_count_time = PlotWidget(self.tab_APD)
        self.graph_count_time.setGeometry(QtCore.QRect(20, 60, 371, 291))
        self.graph_count_time.setStyleSheet("border: 1px solid black")
        self.graph_count_time.setObjectName("graph_count_time")
        self.btn_on_off = QtWidgets.QPushButton(self.tab_APD)
        self.btn_on_off.setGeometry(QtCore.QRect(240, 460, 311, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_on_off.setFont(font)
        self.btn_on_off.setText("ON/OFF")
        self.btn_on_off.setCheckable(True)
        self.btn_on_off.setObjectName("btn_on_off")
        self.graph_fft = PlotWidget(self.tab_APD)
        self.graph_fft.setGeometry(QtCore.QRect(410, 60, 371, 291))
        self.graph_fft.setStyleSheet("border: 1px solid black")
        self.graph_fft.setObjectName("graph_fft")
        self.label = QtWidgets.QLabel(self.tab_APD)
        self.label.setGeometry(QtCore.QRect(20, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_APD)
        self.label_2.setGeometry(QtCore.QRect(290, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txt_time_scale = QtWidgets.QTextEdit(self.tab_APD)
        self.txt_time_scale.setGeometry(QtCore.QRect(190, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_time_scale.setFont(font)
        self.txt_time_scale.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_time_scale.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_time_scale.setObjectName("txt_time_scale")
        self.btn_send = QtWidgets.QPushButton(self.tab_APD)
        self.btn_send.setGeometry(QtCore.QRect(700, 10, 71, 41))
        self.btn_send.setText("Send")
        self.btn_send.setObjectName("btn_send")
        self.btn_find_peak = QtWidgets.QPushButton(self.tab_APD)
        self.btn_find_peak.setGeometry(QtCore.QRect(680, 370, 93, 28))
        self.btn_find_peak.setText("Find Peak")
        self.btn_find_peak.setObjectName("btn_find_peak")
        self.tabWidget.addTab(self.tab_APD, "APD")

        """TAB VACIO"""
        self.tab_vacio = QtWidgets.QWidget()
        self.tab_vacio.setObjectName("tab_vacio")
        self.label_3 = QtWidgets.QLabel(self.tab_vacio)
        self.label_3.setGeometry(QtCore.QRect(70, 40, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_vacio)
        self.label_4.setGeometry(QtCore.QRect(60, 110, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_vacio)
        self.label_5.setGeometry(QtCore.QRect(50, 180, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_vacio)
        self.label_6.setGeometry(QtCore.QRect(85, 330, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_vacio)
        self.label_7.setGeometry(QtCore.QRect(90, 250, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_vacio)
        self.label_8.setGeometry(QtCore.QRect(390, 180, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_vacio)
        self.label_9.setGeometry(QtCore.QRect(390, 320, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_vacio)
        self.label_10.setGeometry(QtCore.QRect(390, 40, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_vacio)
        self.label_11.setGeometry(QtCore.QRect(390, 250, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_vacio)
        self.label_12.setGeometry(QtCore.QRect(390, 110, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.txt_temperature = QtWidgets.QTextBrowser(self.tab_vacio)
        self.txt_temperature.setGeometry(QtCore.QRect(230, 330, 141, 31))
        self.txt_temperature.setObjectName("txt_temperature")
        self.txt_bomb_power = QtWidgets.QTextBrowser(self.tab_vacio)
        self.txt_bomb_power.setGeometry(QtCore.QRect(230, 260, 141, 31))
        self.txt_bomb_power.setObjectName("txt_bomb_power")
        self.txt_valve_state = QtWidgets.QTextBrowser(self.tab_vacio)
        self.txt_valve_state.setGeometry(QtCore.QRect(230, 190, 141, 31))
        self.txt_valve_state.setPlaceholderText("")
        self.txt_valve_state.setObjectName("txt_valve_state")
        self.txt_motor_velocity = QtWidgets.QTextBrowser(self.tab_vacio)
        self.txt_motor_velocity.setGeometry(QtCore.QRect(230, 120, 141, 31))
        self.txt_motor_velocity.setObjectName("txt_motor_velocity")
        self.txt_bomb_pressure = QtWidgets.QTextBrowser(self.tab_vacio)
        self.txt_bomb_pressure.setGeometry(QtCore.QRect(230, 50, 141, 31))
        self.txt_bomb_pressure.setObjectName("txt_bomb_pressure")
        self.rbtn_on_off_temperature = QtWidgets.QRadioButton(self.tab_vacio)
        self.rbtn_on_off_temperature.setGeometry(QtCore.QRect(470, 340, 95, 20))
        self.rbtn_on_off_temperature.setCheckable(True)
        self.rbtn_on_off_temperature.setChecked(False)
        self.rbtn_on_off_temperature.setAutoExclusive(False)
        self.rbtn_on_off_temperature.setObjectName("rbtn_on_off_temperature")
        self.rbtn_on_off_bomb_power = QtWidgets.QRadioButton(self.tab_vacio)
        self.rbtn_on_off_bomb_power.setGeometry(QtCore.QRect(470, 270, 95, 20))
        self.rbtn_on_off_bomb_power.setCheckable(True)
        self.rbtn_on_off_bomb_power.setChecked(False)
        self.rbtn_on_off_bomb_power.setAutoExclusive(False)
        self.rbtn_on_off_bomb_power.setObjectName("rbtn_on_off_bomb_power")
        self.tabWidget.addTab(self.tab_vacio, "")

        """"TAB REGISTROS"""
        self.tab_registro = QtWidgets.QWidget()
        self.tab_registro.setObjectName("tab_registro")
        self.label_13 = QtWidgets.QLabel(self.tab_registro)
        self.label_13.setGeometry(QtCore.QRect(180, 0, 481, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_registro)
        self.radioButton_3.setGeometry(QtCore.QRect(140, 90, 111, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab_registro)
        self.radioButton_4.setGeometry(QtCore.QRect(260, 90, 111, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.tab_registro)
        self.radioButton_5.setGeometry(QtCore.QRect(380, 90, 111, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setAutoExclusive(False)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.tab_registro)
        self.radioButton_6.setGeometry(QtCore.QRect(500, 90, 111, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setAutoExclusive(False)
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.tab_registro)
        self.radioButton_7.setGeometry(QtCore.QRect(260, 130, 111, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_7.setFont(font)
        self.radioButton_7.setAutoExclusive(False)
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.tab_registro)
        self.radioButton_8.setGeometry(QtCore.QRect(140, 130, 111, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_8.setFont(font)
        self.radioButton_8.setAutoExclusive(False)
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.tab_registro)
        self.radioButton_9.setGeometry(QtCore.QRect(380, 130, 111, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_9.setFont(font)
        self.radioButton_9.setAutoExclusive(False)
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.tab_registro)
        self.radioButton_10.setGeometry(QtCore.QRect(500, 130, 111, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_10.setFont(font)
        self.radioButton_10.setAutoExclusive(False)
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_11 = QtWidgets.QRadioButton(self.tab_registro)
        self.radioButton_11.setGeometry(QtCore.QRect(260, 170, 111, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_11.setFont(font)
        self.radioButton_11.setAutoExclusive(False)
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(self.tab_registro)
        self.radioButton_12.setGeometry(QtCore.QRect(140, 170, 111, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_12.setFont(font)
        self.radioButton_12.setAutoExclusive(False)
        self.radioButton_12.setObjectName("radioButton_12")
        self.radioButton_13 = QtWidgets.QRadioButton(self.tab_registro)
        self.radioButton_13.setGeometry(QtCore.QRect(380, 170, 111, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_13.setFont(font)
        self.radioButton_13.setAutoExclusive(False)
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(self.tab_registro)
        self.radioButton_14.setGeometry(QtCore.QRect(500, 170, 111, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_14.setFont(font)
        self.radioButton_14.setAutoExclusive(False)
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_15 = QtWidgets.QRadioButton(self.tab_registro)
        self.radioButton_15.setGeometry(QtCore.QRect(330, 210, 111, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_15.setFont(font)
        self.radioButton_15.setAutoExclusive(False)
        self.radioButton_15.setObjectName("radioButton_15")
        self.label_14 = QtWidgets.QLabel(self.tab_registro)
        self.label_14.setGeometry(QtCore.QRect(30, 370, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.txt_sample_rate = QtWidgets.QTextEdit(self.tab_registro)
        self.txt_sample_rate.setGeometry(QtCore.QRect(260, 390, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_sample_rate.setFont(font)
        self.txt_sample_rate.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_sample_rate.setObjectName("txt_sample_rate")
        self.label_15 = QtWidgets.QLabel(self.tab_registro)
        self.label_15.setGeometry(QtCore.QRect(330, 380, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.txt_path = QtWidgets.QTextEdit(self.tab_registro)
        self.txt_path.setGeometry(QtCore.QRect(30, 430, 171, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txt_path.setFont(font)
        self.txt_path.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_path.setObjectName("txt_path")
        self.btn_inspect = QtWidgets.QPushButton(self.tab_registro)
        self.btn_inspect.setGeometry(QtCore.QRect(210, 430, 171, 30))
        self.btn_inspect.setObjectName("btn_inspect")
        self.btn_inspect.clicked.connect(self.search_folder)
        self.cb_formats = QtWidgets.QComboBox(self.tab_registro)
        self.cb_formats.setGeometry(QtCore.QRect(30, 480, 351, 41))
        self.cb_formats.setCurrentText("")
        self.cb_formats.setObjectName("cb_formats")
        self.btn_start_register = QtWidgets.QPushButton(self.tab_registro)
        self.btn_start_register.setGeometry(QtCore.QRect(420, 389, 301, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_start_register.setFont(font)
        self.btn_start_register.setCheckable(True)
        self.btn_start_register.setObjectName("btn_start_register")
        self.tabWidget.addTab(self.tab_registro, "")

        """TAB ESI"""
        self.tab_ESI = QtWidgets.QWidget()
        self.tab_ESI.setObjectName("tab_ESI")
        self.camera = QtWidgets.QGraphicsView(self.tab_ESI)
        self.camera.setGeometry(QtCore.QRect(20, 20, 401, 451))
        self.camera.setObjectName("camera")
        self.label_22 = QtWidgets.QLabel(self.tab_ESI)
        self.label_22.setGeometry(QtCore.QRect(430, 30, 141, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_ESI)
        self.label_23.setGeometry(QtCore.QRect(430, 80, 151, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab_ESI)
        self.label_24.setGeometry(QtCore.QRect(430, 120, 201, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_ESI)
        self.label_25.setGeometry(QtCore.QRect(640, 40, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.txt_voltage = QtWidgets.QTextBrowser(self.tab_ESI)
        self.txt_voltage.setGeometry(QtCore.QRect(640, 90, 131, 31))
        self.txt_voltage.setObjectName("txt_voltage")
        self.txt_motor = QtWidgets.QTextBrowser(self.tab_ESI)
        self.txt_motor.setGeometry(QtCore.QRect(640, 170, 131, 31))
        self.txt_motor.setObjectName("txt_motor")
        self.btn_on_off_motor = QtWidgets.QPushButton(self.tab_ESI)
        self.btn_on_off_motor.setGeometry(QtCore.QRect(480, 340, 261, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_on_off_motor.setFont(font)
        self.btn_on_off_motor.setCheckable(True)
        self.btn_on_off_motor.setAutoDefault(False)
        self.btn_on_off_motor.setDefault(False)
        self.btn_on_off_motor.setFlat(False)
        self.btn_on_off_motor.setObjectName("btn_on_off_motor")
        self.tabWidget.addTab(self.tab_ESI, "")

        """TAB TRAMPA"""
        self.tab_trampa = QtWidgets.QWidget()
        self.tab_trampa.setObjectName("tab_trampa")
        self.graph_voltage = QtWidgets.QWidget(self.tab_trampa)
        self.graph_voltage.setGeometry(QtCore.QRect(20, 20, 431, 611))
        self.graph_voltage.setStyleSheet("border: 1px solid black")
        self.graph_voltage.setObjectName("graph_voltage")
        self.btn_on_off_2 = QtWidgets.QPushButton(self.tab_trampa)
        self.btn_on_off_2.setGeometry(QtCore.QRect(530, 50, 181, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_on_off_2.setFont(font)
        self.btn_on_off_2.setCheckable(True)
        self.btn_on_off_2.setObjectName("btn_on_off_2")
        self.label_17 = QtWidgets.QLabel(self.tab_trampa)
        self.label_17.setGeometry(QtCore.QRect(470, 220, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.txt_mass = QtWidgets.QLineEdit(self.tab_trampa)
        self.txt_mass.setGeometry(QtCore.QRect(640, 221, 113, 31))
        self.txt_mass.setObjectName("txt_mass")
        self.txt_charge = QtWidgets.QLineEdit(self.tab_trampa)
        self.txt_charge.setGeometry(QtCore.QRect(640, 270, 113, 31))
        self.txt_charge.setObjectName("txt_charge")
        self.txt_q = QtWidgets.QLineEdit(self.tab_trampa)
        self.txt_q.setGeometry(QtCore.QRect(640, 320, 113, 31))
        self.txt_q.setObjectName("txt_q")
        self.txt_voltage_2 = QtWidgets.QLineEdit(self.tab_trampa)
        self.txt_voltage_2.setGeometry(QtCore.QRect(640, 370, 113, 31))
        self.txt_voltage_2.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.txt_voltage_2.setReadOnly(True)
        self.txt_voltage_2.setObjectName("txt_voltage_2")
        self.txt_freq = QtWidgets.QLineEdit(self.tab_trampa)
        self.txt_freq.setGeometry(QtCore.QRect(640, 420, 113, 31))
        self.txt_freq.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.txt_freq.setReadOnly(True)
        self.txt_freq.setObjectName("txt_freq")
        self.label_18 = QtWidgets.QLabel(self.tab_trampa)
        self.label_18.setGeometry(QtCore.QRect(470, 270, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_trampa)
        self.label_19.setGeometry(QtCore.QRect(470, 320, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_trampa)
        self.label_20.setGeometry(QtCore.QRect(470, 370, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_trampa)
        self.label_21.setGeometry(QtCore.QRect(470, 420, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.btn_calculate = QtWidgets.QPushButton(self.tab_trampa)
        self.btn_calculate.setGeometry(QtCore.QRect(560, 480, 93, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_calculate.setFont(font)
        self.btn_calculate.setObjectName("btn_calculate")
        self.tabWidget.addTab(self.tab_trampa, "")

        """TAB PROCESAMIENTO"""
        self.tab_procesamiento = QtWidgets.QWidget()
        self.tab_procesamiento.setObjectName("tab_procesamiento")
        self.graph_mass_charge_time = PlotWidget(self.tab_procesamiento)
        self.graph_mass_charge_time.setGeometry(QtCore.QRect(20, 20, 751, 391))
        self.graph_mass_charge_time.setStyleSheet("border: 1px solid black")
        self.graph_mass_charge_time.setObjectName("graph_mass_charge_time")
        self.label_16 = QtWidgets.QLabel(self.tab_procesamiento)
        self.label_16.setGeometry(QtCore.QRect(20, 500, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.txt_electro_gun_power = QtWidgets.QTextEdit(self.tab_procesamiento)
        self.txt_electro_gun_power.setGeometry(QtCore.QRect(220, 516, 104, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_electro_gun_power.setFont(font)
        self.txt_electro_gun_power.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_electro_gun_power.setObjectName("txt_electro_gun_power")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_procesamiento)
        self.pushButton_9.setGeometry(QtCore.QRect(490, 490, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setText("ON / OFF")
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.tabWidget.addTab(self.tab_procesamiento, "")

        """TAB MEDICIONES TEMPERATURA"""
        self.tab_mediciones_temperatura = QtWidgets.QWidget()
        self.tab_mediciones_temperatura.setObjectName("tab_mediciones_temperatura")
        self.tabWidget.addTab(self.tab_mediciones_temperatura, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def search_folder(self):
        fname=QFileDialog.getExistingDirectory(caption = "Select Directory")
        self.txt_path.setText(fname)

    def graph():  #failing 
        while True:
            print("A")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Time Scale:"))
        self.label_2.setText(_translate("MainWindow", "[μs]"))
        self.label_3.setText(_translate("MainWindow", "Bomb Pressure:"))
        self.label_4.setText(_translate("MainWindow", "Velocidad Motor:"))
        self.label_5.setText(_translate("MainWindow", "Valve State (A/C):"))
        self.label_6.setText(_translate("MainWindow", "Temperature:"))
        self.label_7.setText(_translate("MainWindow", "Bomb Power:"))
        self.label_9.setText(_translate("MainWindow", "[ºC]"))
        self.label_10.setText(_translate("MainWindow", "[kPa]"))
        self.label_11.setText(_translate("MainWindow", "[W]"))
        self.label_12.setText(_translate("MainWindow", "[RPM]"))
        self.rbtn_on_off_temperature.setText(_translate("MainWindow", "ON/OFF"))
        self.rbtn_on_off_bomb_power.setText(_translate("MainWindow", "ON/OFF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_vacio), _translate("MainWindow", "Vacío"))
        self.label_13.setText(_translate("MainWindow", "List of variables to register:"))
        self.radioButton_3.setText(_translate("MainWindow", "Variable 1"))
        self.radioButton_4.setText(_translate("MainWindow", "Variable 4"))
        self.radioButton_5.setText(_translate("MainWindow", "Variable 7"))
        self.radioButton_6.setText(_translate("MainWindow", "Variable 10"))
        self.radioButton_7.setText(_translate("MainWindow", "Variable 5"))
        self.radioButton_8.setText(_translate("MainWindow", "Variable 2"))
        self.radioButton_9.setText(_translate("MainWindow", "Variable 8"))
        self.radioButton_10.setText(_translate("MainWindow", "Variable 11"))
        self.radioButton_11.setText(_translate("MainWindow", "Variable 6"))
        self.radioButton_12.setText(_translate("MainWindow", "Variable 3"))
        self.radioButton_13.setText(_translate("MainWindow", "Variable 9"))
        self.radioButton_14.setText(_translate("MainWindow", "Variable 12"))
        self.radioButton_15.setText(_translate("MainWindow", "Variable 13"))
        self.label_14.setText(_translate("MainWindow", "Frecuencia de Muestreo:"))
        self.label_15.setText(_translate("MainWindow", "[Hz]"))
        self.btn_inspect.setText(_translate("MainWindow", "Inspect"))
        self.btn_start_register.setText(_translate("MainWindow", "Start Register"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_registro), _translate("MainWindow", "Registro"))
        self.label_22.setText(_translate("MainWindow", "Valve (A/C):"))
        self.label_23.setText(_translate("MainWindow", "Voltaje Fuente:"))
        self.label_24.setText(_translate("MainWindow", "Periodo Accionamiento Motor:"))
        self.label_25.setText(_translate("MainWindow", "Valve_output"))
        self.btn_on_off_motor.setText(_translate("MainWindow", "Motor ON/OFF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ESI), _translate("MainWindow", "ESI"))
        self.btn_on_off_2.setText(_translate("MainWindow", "ON/OFF"))
        self.label_17.setText(_translate("MainWindow", "Mass:"))
        self.label_18.setText(_translate("MainWindow", "Carga:"))
        self.label_19.setText(_translate("MainWindow", "q:"))
        self.label_20.setText(_translate("MainWindow", "Voltage:"))
        self.label_21.setText(_translate("MainWindow", "Frequency:"))
        self.btn_calculate.setText(_translate("MainWindow", "Calculate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_trampa), _translate("MainWindow", "Trampa"))
        self.label_16.setText(_translate("MainWindow", "Electron Gun Power:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_procesamiento), _translate("MainWindow", "Procesamiento"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mediciones_temperatura), _translate("MainWindow", "Mediciones de Temperatura"))

if __name__ == "__main__":
    def run():
        import sys
        # threading.Thread(target=Ui_MainWindow.graph).start()
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
    threading.Thread(target=run).start()
    

